### ISSUE TITLE
Strategy for complex templates

### ISSUE THREAD

**Issue by crybat** [sparkphp/project#6]
Hi,

Hope this is the correct place for this.

What is Spark's answer to complex layouts?
For example, you need secondary data like user data, latest news, etc?

I'm inclined to share a common domain service compositionally - which is responsible for fetching all that tangential data - to the main service you're calling from the action and have it add that data to the "main" payload.

But I'd value more an opinion from the source.

Thanks.

**Comment by shadowhand** [comment]
@crybat we include an option for [Plates](http://platesphp.com/) for templating complex layouts. For creating the various content, I would suggest either using an inherited abstract domain that is injected with the services you need to generate the additional content or composing each domain with those services by way of a trait.

**Comment by crybat** [comment]
Yup, saw Plates. Pretty cool.
Was more interested in the second part of your answer. Both make sense, kinda what I was thinking.
Thanks.

**Comment by bvisness** [comment]
Sounds like you got your question answered, so I'm closing this.
